Update partners.txt
Delitefully/DiscordLists pull request #197
Opened 2022-12-04 22:18 UTC by DodoSeal

DV Plays is a YouTuber who owns a Partnered Discord Server. I added his Invite link since I wasn't there. I may have misunderstood the purpose of this file though.

2022-12-05 22:17 UTC, Techy requested changes
This needs to be alphabetically sorted.

2022-12-09 03:54 UTC, DodoSeal commented
> This needs to be alphabetically sorted.

Oops sorry

2022-12-09 22:30 UTC, DodoSeal commented
When I have time, yes

2022-12-12 19:28 UTC, Techy approved these changes

2022-12-12 19:29 UTC, merged